In [2]:
import requests
import pandas as pd
from IPython.display import display

In [3]:
url = "https://www.thesportsdb.com/api/v1/json/3/search_all_teams.php?l=English%20Premier%20League"

response = requests.get(url)

print("Status Code:", response.status_code)

data = response.json()

print(data.keys())

Status Code: 200
dict_keys(['teams'])

In [4]:
df = pd.DataFrame(data["teams"])

print("Rows and Columns:", df.shape)
print("Number of Columns:", len(df.columns))

Rows and Columns: (10, 64)
Number of Columns: 64

In [5]:
df.fillna("N/A", inplace=True)

df.drop_duplicates(inplace=True)

print("After Cleaning:", df.shape)

After Cleaning: (10, 64)

In [6]:
display(df.head())

,idTeam,idESPN,idAPIfootball,intLoved,strTeam,strTeamAlternate,strTeamShort,intFormedYear,strSport,strLeague,...,strBadge,strLogo,strFanart1,strFanart2,strFanart3,strFanart4,strBanner,strEquipment,strYoutube,strLocked
0,133604,359,42,10,Arsenal,"Arsenal Football Club, AFC, Arsenal FC",ARS,1892,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/ArsenalTour,unlocked
1,133601,4328,66,N/A,Aston Villa,Aston Villa FC,AVL,1874,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/avfcofficial,unlocked
2,134301,349,35,2,Bournemouth,"AFC Bournemouth, Athletic Football Club Bourne...",BOU,1890,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/officiacherries,unlocked
3,134355,337,55,1,Brentford,"Brentford Football Club, Brentford FC, BFC",BRE,1889,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/brentfordfc,unlocked
4,133619,331,51,1,Brighton and Hove Albion,"Brighton & Hove Albion Football Club, Brighton...",BRI,1901,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/officialbhafc,unlocked

In [7]:
df.to_csv("sports_teams.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [12]:
csv_df = pd.read_csv("sports_teams.csv")

print(csv_df.shape)

display(csv_df.head())

(10, 64)

,idTeam,idESPN,idAPIfootball,intLoved,strTeam,strTeamAlternate,strTeamShort,intFormedYear,strSport,strLeague,...,strBadge,strLogo,strFanart1,strFanart2,strFanart3,strFanart4,strBanner,strEquipment,strYoutube,strLocked
0,133604,359,42,10.0,Arsenal,"Arsenal Football Club, AFC, Arsenal FC",ARS,1892,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/ArsenalTour,unlocked
1,133601,4328,66,NaN,Aston Villa,Aston Villa FC,AVL,1874,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/avfcofficial,unlocked
2,134301,349,35,2.0,Bournemouth,"AFC Bournemouth, Athletic Football Club Bourne...",BOU,1890,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/officiacherries,unlocked
3,134355,337,55,1.0,Brentford,"Brentford Football Club, Brentford FC, BFC",BRE,1889,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/brentfordfc,unlocked
4,133619,331,51,1.0,Brighton and Hove Albion,"Brighton & Hove Albion Football Club, Brighton...",BRI,1901,Soccer,English Premier League,...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/l...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/f...,https://r2.thesportsdb.com/images/media/team/b...,https://r2.thesportsdb.com/images/media/team/e...,www.youtube.com/user/officialbhafc,unlocked

In [10]:
import os

print(os.getcwd())

C:\Users\kanis

In [11]:
import os

print(os.path.exists("sports_teams.csv"))

True

In [14]:
import requests
import pandas as pd

url = "https://www.thesportsdb.com/api/v1/json/3/search_all_teams.php?l=English%20Premier%20League"

try:
    response = requests.get(url, timeout=10)

    # Check for HTTP errors
    response.raise_for_status()

    data = response.json()

    if "teams" not in data or data["teams"] is None:
        print("No team data found.")
    else:
        df = pd.DataFrame(data["teams"])

        # Data Cleaning
        df.fillna("N/A", inplace=True)
        df.drop_duplicates(inplace=True)

        # Save CSV
        df.to_csv("sports_teams.csv", index=False)

        print("Data collected successfully!")
        print("Dataset Shape:", df.shape)

except requests.exceptions.Timeout:
    print("Request timed out.")

except requests.exceptions.ConnectionError:
    print("No internet connection.")

except requests.exceptions.HTTPError as e:
    print("HTTP Error:", e)

except requests.exceptions.RequestException as e:
    print("Request Error:", e)

except Exception as e:
    print("Unexpected Error:", e)

Data collected successfully!
Dataset Shape: (10, 64)